version: '3'

services:
  redis:
    image: 'redis:7.0-alpine'
    ports:
      - '6379:6379'
    volumes:
      - redis_db:/data
  app:
    build:
      context: .
    restart: on-failure
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=
      - DEBUG=app:exchange:*
    volumes:
      - node_modules:/app/node_modules
    depends_on:
      - redis

volumes:
  redis_db:
  node_modules:
